version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: CI=true yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test