version: 2.1
orbs:
  node: circleci/node:20.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: CI=true yarn test
workflows:
  build-and-test:
    jobs:
      - test