version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: "20.0.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  publish:
    executor:
      name: node/default
      tag: "20.0.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Publish to NPM
          command: |
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
workflows:
  test:
    jobs:
      - test
  tagged-build:
    jobs:
      - publish:
          filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*/
